language: csharp
solution: source/Handlebars.sln
install:
  - nuget restore source/Handlebars.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release source/Handlebars.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./source/Handlebars.Test/bin/Release/Handlebars.Test.dll
notifications:
  email:
    - gabriel.lemire@gmail.com
